# Default values for ingress-routing.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ingress:
  - path: /api
    serviceName: login-service-production-svc
    servicePort: 80
  - serviceName: login-app-production-svc
    servicePort: 80
