kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: login-service-deployment
  labels:
    app: login-service-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: login-service-app
  template:
    metadata:
      labels:
        app: login-service-app
    spec:
      containers:
      - name: login-service-app
        image: acrivanbnywestus.azurecr.io/service:latest # will be {{ .Values... }} in Helm charts
        volumeMounts:
        - name: secrets
          mountPath: /secrets
          readOnly: true
        ports:
           - containerPort: 4201
        resources:
         requests:
          cpu: "500m" # X/1000 of a CPU
      initContainers:
      - name: keyvault-agent
        image: acrivanbnywestus.azurecr.io/hexadite:latest # will be {{ .Values... }} in Helm charts
        env:
        - name: VAULT_BASE_URL
          value: https://ivanbny-deploy-kv.vault.azure.net # will be {{ .Values... }} in Helm charts
        - name: SERVICE_PRINCIPLE_FILE_PATH
          value: /host/azure.json
        - name: SECRETS_FOLDER
          value: /secrets
        - name: SECRETS_KEYS
          value: mt-aad-password
        {{- range $index, item := .Values.yaml }}  #looping through values in ConfigMap
          - name: {{ item.name }}
            valueFrom:
              configMapKeyRef:
                name: configs
                key: {{ item.key }}
        {{- end }}

        volumeMounts:
        - name: secrets
          mountPath: /secrets

        - name: host-sp
          mountPath: /host/azure.json
          readOnly: true

      imagePullSecrets:
        - name: acr-credentials

      volumes:
      - name: secrets
        emptyDir:
          # we want the secrets to reside only in-memory
          medium: Memory

      - name: host-sp
        hostPath:
          # this file contains the cluster service-principal, it exists on every node by default
          path: /etc/kubernetes/azure.json
          #type: File # commented out because current cubctl doesn't understand it.
